version: "3.8"
services:
  database:
    image: postgres:alpine
    container_name: dev-postgres-ionia
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ds_ionia
    ports:
      - 5439:5439
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: