spring:
  profiles:
    active: ${APP_PROFILE:test}
  jpa:
    open-in-view: false
  main:
    allow-circular-references: true

cors:
  origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

aws:
  sqs:
    access-key: AKIARYPVGQCX7FSQR4FN
    secret-key: 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
    region: sa-east
    queues:
      address:
        queue-url: https://sqs.sa-east-1.amazonaws.com/121310183599/demacia-address.fifo
      client-account:
        queue-url: https://sqs.sa-east-1.amazonaws.com/121310183599/demacia-client-account.fifo
      drink:
        queue-url: https://sqs.sa-east-1.amazonaws.com/121310183599/demacia-drink.fifo
      neighbourhood:
        queue-url: https://sqs.sa-east-1.amazonaws.com/121310183599/demacia-neighbourhood.fifo
      order:
        queue-url: https://sqs.sa-east-1.amazonaws.com/121310183599/demacia-order.fifo
      size:
        queue-url: https://sqs.sa-east-1.amazonaws.com/121310183599/demacia-size.fifo
      soup:
        queue-url: https://sqs.sa-east-1.amazonaws.com/121310183599/demacia-soup.fifo